[providers]
php = "8.2"

[phases.setup]
nixPkgs = ["...", "apache2", "php82Packages.composer"]

[phases.build]
cmds = [
    "composer install --no-dev --optimize-autoloader",
    "php artisan config:cache",
    "php artisan route:cache", 
    "php artisan view:cache"
]

[start]
cmd = "apache2-foreground"
