[providers]
php = "8.2"
nodejs = "18"

[phases.build]
cmds = [
    "npm ci",
    "npm run build",
    "composer install --no-dev --optimize-autoloader",
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
